apiVersion: fabricops.my.domain/v1alpha1
kind: FabricNetwork
metadata:
  labels:
    app.kubernetes.io/name: fabricops
    app.kubernetes.io/managed-by: kustomize
  name: fabricnetwork-sample
spec:
  global:
    fabricVersion: "3.1.0"
    tls: true

  orgs:
    - organization:
        name: Orderer
        domain: orderer.example.com
        mspName: OrdererMSP
      ca:
        db: sqlite
      orderers:
        - groupName: group1
          type: raft
          instances: 2
          prefix: orderer

    - organization:
        name: BankA
        domain: banka.example.com
        mspName: BankAMSP
      ca:
        db: postgres
      peer:
        instances: 2
        db: CouchDb
        prefix: peer

  channels:
    - name: settlement
      orgs:
        - name: BankA
          peers: ["peer0", "peer1"]

  chaincodes:
    - name: settlement
      version: "0.0.1"
      channel: settlement
      image: settlement-engine:latest
